update

diff --git a/dotfiles/local/bin/gitsync b/dotfiles/local/bin/gitsync
--- a/dotfiles/local/bin/gitsync
+++ b/dotfiles/local/bin/gitsync
@@ -1,18 +1,20 @@
-#!/usr/bin/sh
+#!/usr/bin/bash
 
 usage_and_exit()
 {
-	2>&1 echo "USAGE: $0 [OPTION]... DIRECTORY"
-	2>&1 echo "Watch for changes in the DIRECTORY, and commit and push them."
-  2>&1 echo ""
-  2>&1 echo "
--h, --help|print this help
--f, --format <fmt>|describe commit messages format. Defaults to \"%d: %f\". The following conversions are supported
-|%f: Replaced by the name of the file modified
-|%e: Replaced by the event(s) which occurred (see EVENTS section of inotifywait(1))
-|%d: Replaced by the output of the \`date\` command
-" | column -t -s '|'
-	exit ${1:-1}
+	(
+	echo "Synchronize a local git repository with the remote every time a file changes"
+	echo ""
+	echo "Usage: $(basename "$0") [OPTION]... DIRECTORY"
+	echo "
+	-h, --help|print this help
+	-f, --format <fmt>|describe commit messages format. Defaults to \"%d: %f\". The following conversions are supported
+	|%f: Replaced by the name of the file modified
+	|%e: Replaced by the event(s) which occurred (see EVENTS section of inotifywait(1))
+	|%d: Replaced by the output of the \`date\` command
+	" | column -t -s '|'
+	) >&2
+	exit "${1:-1}"
 }
 
 opt_format="%d: %f"
@@ -26,8 +28,8 @@ while [[ $# -gt 0 ]]; do
     -h|--help)
       usage_and_exit 0
       ;;
-    -*|--*)
-			2>&1 printf "Error: Unknown argument '$1'\n\n" && usage_and_exit 1
+    -*)
+			2>&1 printf "Error: Unknown argument '%s'\n\n" "$1" && usage_and_exit 1
       ;;
     *)
       break
@@ -41,19 +43,16 @@ if [[ $# -lt 1 ]]; then
 fi
 
 for dir in "$@"; do
-	(
-		cd $dir
-		git pull -q
-	)
+	(cd "$dir" && git pull -q)
 done
 
-inotifywait -q -e close_write,delete --exclude "4913|\.git\/" -r $1 -m | while read -r directory events filename; do
+inotifywait -q -e close_write,delete --exclude "4913|\.git\/" -r "$1" -m | while read -r directory events filename; do
 	(
 		msg="$opt_format"
 		msg="${msg//"%f"/"$filename"}"
 		msg="${msg//"%e"/"$events"}"
-		msg="${msg//"%d"/"`date`"}"
-		cd $directory
+		msg="${msg//"%d"/"$(date)"}"
+		cd "$directory" || exit
 		git add .
 		git commit -q -m "$msg"
 		git push
